/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAiLabRouteImport } from './routes/admin/ai-lab'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as BookingFormTokenRouteImport } from './routes/booking.form.$token'
import { Route as BookConfirmationIdRouteImport } from './routes/book/confirmation/$id'
import { Route as ApiTelegramAgentKeyRouteImport } from './routes/api.telegram.$agentKey'
import { Route as ApiPublicHealthCheckRouteImport } from './routes/api.public.health-check'
import { Route as ApiCronWaSummaryRefreshRouteImport } from './routes/api.cron.wa-summary-refresh'
import { Route as ApiCronSyncExploreRouteImport } from './routes/api.cron.sync-explore'
import { Route as ApiCronRunArticleSchedulesRouteImport } from './routes/api.cron.run-article-schedules'
import { Route as ApiCronProcessWaQueueRouteImport } from './routes/api.cron.process-wa-queue'
import { Route as ApiCronWaQueueSafetyNetRouteImport } from './routes/api.cron.wa-queue-safety-net'
import { Route as ApiCronExpireBookingsRouteImport } from './routes/api.cron.expire-bookings'
import { Route as ApiCronBookingStuckMonitorRouteImport } from './routes/api.cron.booking-stuck-monitor'
import { Route as ApiBookingInvoiceIdRouteImport } from './routes/api.booking-invoice.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as BookConfirmationIdChatRouteImport } from './routes/book/confirmation/$id.chat'
import { Route as ApiPublicBookingFormTokenRouteImport } from './routes/api.public.booking-form.$token'
import { Route as ApiBookingInvoiceIdSendRouteImport } from './routes/api.booking-invoice.$id.send'
import { Route as ApiPublicBookingFormTokenRouteImport } from './routes/api.public.booking-form.$token'
import { Route as BookConfirmationIdChatRouteImport } from './routes/book/confirmation/$id.chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiLabRoute = AdminAiLabRouteImport.update({
  id: '/ai-lab',
  path: '/ai-lab',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingFormLogsRoute = AdminBookingFormLogsRouteImport.update({
  id: '/booking-form-logs',
  path: '/booking-form-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatbotTrainingRoute = AdminChatbotTrainingRouteImport.update({
  id: '/chatbot-training',
  path: '/chatbot-training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompetitorPricesRoute = AdminCompetitorPricesRouteImport.update({
  id: '/competitor-prices',
  path: '/competitor-prices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentManagerRoute = AdminContentManagerRouteImport.update({
  id: '/content-manager',
  path: '/content-manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExploreRoute = AdminExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHandoffRoute = AdminHandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingCalendarRoute = AdminPricingCalendarRouteImport.update({
  id: '/pricing-calendar',
  path: '/pricing-calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoutingDebugRoute = AdminRoutingDebugRouteImport.update({
  id: '/routing-debug',
  path: '/routing-debug',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTelegramRoute = AdminTelegramRouteImport.update({
  id: '/telegram',
  path: '/telegram',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalkthroughRoute = AdminWalkthroughRouteImport.update({
  id: '/walkthrough',
  path: '/walkthrough',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebchatRoute = AdminWebchatRouteImport.update({
  id: '/webchat',
  path: '/webchat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappCorrectionsRoute =
  AdminWhatsappCorrectionsRouteImport.update({
    id: '/whatsapp-corrections',
    path: '/whatsapp-corrections',
    getParentRoute: () => AdminRoute,
  } as any)
const ApiDebugDbRoute = ApiDebugDbRouteImport.update({
  id: '/api/debug-db',
  path: '/api/debug-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvolutionRoute = ApiEvolutionRouteImport.update({
  id: '/api/evolution',
  path: '/api/evolution',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlacePhotoRoute = ApiPlacePhotoRouteImport.update({
  id: '/api/place-photo',
  path: '/api/place-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteRoute = ApiPublicSiteRouteImport.update({
  id: '/api/public-site',
  path: '/api/public-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteDataRoute = ApiPublicSiteDataRouteImport.update({
  id: '/api/public-site-data',
  path: '/api/public-site-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueueWorkerRoute = ApiQueueWorkerRouteImport.update({
  id: '/api/queue-worker',
  path: '/api/queue-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncExploreRoute = ApiCronSyncExploreRouteImport.update({
  id: '/api/cron/sync-explore',
  path: '/api/cron/sync-explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRunArticleSchedulesRoute =
  ApiCronRunArticleSchedulesRouteImport.update({
    id: '/api/cron/run-article-schedules',
    path: '/api/cron/run-article-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronSyncExploreRoute = ApiCronSyncExploreRouteImport.update({
  id: '/api/cron/sync-explore',
  path: '/api/cron/sync-explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronWaQueueSafetyNetRoute = ApiCronWaQueueSafetyNetRouteImport.update({
  id: '/api/cron/wa-queue-safety-net',
  path: '/api/cron/wa-queue-safety-net',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronExpireBookingsRoute = ApiCronExpireBookingsRouteImport.update({
  id: '/api/cron/expire-bookings',
  path: '/api/cron/expire-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronBookingStuckMonitorRoute =
  ApiCronBookingStuckMonitorRouteImport.update({
    id: '/api/cron/booking-stuck-monitor',
    path: '/api/cron/booking-stuck-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBookingInvoiceIdRoute = ApiBookingInvoiceIdRouteImport.update({
  id: '/api/booking-invoice/$id',
  path: '/api/booking-invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookConfirmationIdRoute = BookConfirmationIdRouteImport.update({
  id: '/book/confirmation/$id',
  path: '/book/confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingFormTokenRoute = BookingFormTokenRouteImport.update({
  id: '/booking/form/$token',
  path: '/booking/form/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBookingInvoiceIdSendRoute = ApiBookingInvoiceIdSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => ApiBookingInvoiceIdRoute,
} as any)
const ApiPublicBookingFormTokenRoute =
  ApiPublicBookingFormTokenRouteImport.update({
    id: '/api/public/booking-form/$token',
    path: '/api/public/booking-form/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const BookConfirmationIdChatRoute = BookConfirmationIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => BookConfirmationIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/connect': typeof ConnectRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-lab': typeof AdminAiLabRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/booking-form-logs': typeof AdminBookingFormLogsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/chatbot-training': typeof AdminChatbotTrainingRoute
  '/admin/competitor-prices': typeof AdminCompetitorPricesRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content-manager': typeof AdminContentManagerRoute
  '/admin/explore': typeof AdminExploreRoute
  '/admin/handoff': typeof AdminHandoffRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pricing-calendar': typeof AdminPricingCalendarRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/routing-debug': typeof AdminRoutingDebugRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/walkthrough': typeof AdminWalkthroughRoute
  '/admin/webchat': typeof AdminWebchatRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/whatsapp-corrections': typeof AdminWhatsappCorrectionsRoute
  '/api/debug-db': typeof ApiDebugDbRoute
  '/api/evolution': typeof ApiEvolutionRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/api/public-site': typeof ApiPublicSiteRoute
  '/api/public-site-data': typeof ApiPublicSiteDataRoute
  '/api/queue-worker': typeof ApiQueueWorkerRoute
  '/api/telegram': typeof ApiTelegramRouteWithChildren
  '/lp/$slug': typeof LpSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/book/': typeof BookIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/booking-invoice/$id': typeof ApiBookingInvoiceIdRouteWithChildren
  '/api/cron/booking-form-followup': typeof ApiCronBookingFormFollowupRoute
  '/api/cron/booking-stuck-monitor': typeof ApiCronBookingStuckMonitorRoute
  '/api/cron/expire-bookings': typeof ApiCronExpireBookingsRoute
  '/api/cron/process-wa-queue': typeof ApiCronProcessWaQueueRoute
  '/api/cron/run-article-schedules': typeof ApiCronRunArticleSchedulesRoute
  '/api/cron/sync-explore': typeof ApiCronSyncExploreRoute
  '/api/cron/wa-queue-safety-net': typeof ApiCronWaQueueSafetyNetRoute
  '/api/cron/wa-summary-refresh': typeof ApiCronWaSummaryRefreshRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
  '/api/telegram/$agentKey': typeof ApiTelegramAgentKeyRoute
  '/book/confirmation/$id': typeof BookConfirmationIdRouteWithChildren
  '/booking/form/$token': typeof BookingFormTokenRoute
  '/api/booking-invoice/$id/send': typeof ApiBookingInvoiceIdSendRoute
  '/api/public/booking-form/$token': typeof ApiPublicBookingFormTokenRoute
  '/book/confirmation/$id/chat': typeof BookConfirmationIdChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/connect': typeof ConnectRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-lab': typeof AdminAiLabRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/booking-form-logs': typeof AdminBookingFormLogsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/chatbot-training': typeof AdminChatbotTrainingRoute
  '/admin/competitor-prices': typeof AdminCompetitorPricesRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content-manager': typeof AdminContentManagerRoute
  '/admin/explore': typeof AdminExploreRoute
  '/admin/handoff': typeof AdminHandoffRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pricing-calendar': typeof AdminPricingCalendarRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/routing-debug': typeof AdminRoutingDebugRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/walkthrough': typeof AdminWalkthroughRoute
  '/admin/webchat': typeof AdminWebchatRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/whatsapp-corrections': typeof AdminWhatsappCorrectionsRoute
  '/api/debug-db': typeof ApiDebugDbRoute
  '/api/evolution': typeof ApiEvolutionRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/api/public-site': typeof ApiPublicSiteRoute
  '/api/public-site-data': typeof ApiPublicSiteDataRoute
  '/api/queue-worker': typeof ApiQueueWorkerRoute
  '/api/telegram': typeof ApiTelegramRouteWithChildren
  '/lp/$slug': typeof LpSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/admin': typeof AdminIndexRoute
  '/book': typeof BookIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/booking-invoice/$id': typeof ApiBookingInvoiceIdRouteWithChildren
  '/api/cron/booking-form-followup': typeof ApiCronBookingFormFollowupRoute
  '/api/cron/booking-stuck-monitor': typeof ApiCronBookingStuckMonitorRoute
  '/api/cron/expire-bookings': typeof ApiCronExpireBookingsRoute
  '/api/cron/process-wa-queue': typeof ApiCronProcessWaQueueRoute
  '/api/cron/run-article-schedules': typeof ApiCronRunArticleSchedulesRoute
  '/api/cron/sync-explore': typeof ApiCronSyncExploreRoute
  '/api/cron/wa-queue-safety-net': typeof ApiCronWaQueueSafetyNetRoute
  '/api/cron/wa-summary-refresh': typeof ApiCronWaSummaryRefreshRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
  '/api/telegram/$agentKey': typeof ApiTelegramAgentKeyRoute
  '/book/confirmation/$id': typeof BookConfirmationIdRouteWithChildren
  '/booking/form/$token': typeof BookingFormTokenRoute
  '/api/booking-invoice/$id/send': typeof ApiBookingInvoiceIdSendRoute
  '/api/public/booking-form/$token': typeof ApiPublicBookingFormTokenRoute
  '/book/confirmation/$id/chat': typeof BookConfirmationIdChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/chat': typeof ChatRoute
  '/connect': typeof ConnectRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/ai-lab': typeof AdminAiLabRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/booking-form-logs': typeof AdminBookingFormLogsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/chatbot-training': typeof AdminChatbotTrainingRoute
  '/admin/competitor-prices': typeof AdminCompetitorPricesRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/content-manager': typeof AdminContentManagerRoute
  '/admin/explore': typeof AdminExploreRoute
  '/admin/handoff': typeof AdminHandoffRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pricing-calendar': typeof AdminPricingCalendarRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/routing-debug': typeof AdminRoutingDebugRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/telegram': typeof AdminTelegramRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/walkthrough': typeof AdminWalkthroughRoute
  '/admin/webchat': typeof AdminWebchatRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/admin/whatsapp-corrections': typeof AdminWhatsappCorrectionsRoute
  '/api/debug-db': typeof ApiDebugDbRoute
  '/api/evolution': typeof ApiEvolutionRoute
  '/api/place-photo': typeof ApiPlacePhotoRoute
  '/api/public-site': typeof ApiPublicSiteRoute
  '/api/public-site-data': typeof ApiPublicSiteDataRoute
  '/api/queue-worker': typeof ApiQueueWorkerRoute
  '/api/telegram': typeof ApiTelegramRouteWithChildren
  '/lp/$slug': typeof LpSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/tour/$slug': typeof TourSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/book/': typeof BookIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/booking-invoice/$id': typeof ApiBookingInvoiceIdRouteWithChildren
  '/api/cron/booking-form-followup': typeof ApiCronBookingFormFollowupRoute
  '/api/cron/booking-stuck-monitor': typeof ApiCronBookingStuckMonitorRoute
  '/api/cron/expire-bookings': typeof ApiCronExpireBookingsRoute
  '/api/cron/process-wa-queue': typeof ApiCronProcessWaQueueRoute
  '/api/cron/run-article-schedules': typeof ApiCronRunArticleSchedulesRoute
  '/api/cron/sync-explore': typeof ApiCronSyncExploreRoute
  '/api/cron/wa-queue-safety-net': typeof ApiCronWaQueueSafetyNetRoute
  '/api/cron/wa-summary-refresh': typeof ApiCronWaSummaryRefreshRoute
  '/api/public/health-check': typeof ApiPublicHealthCheckRoute
  '/api/telegram/$agentKey': typeof ApiTelegramAgentKeyRoute
  '/book/confirmation/$id': typeof BookConfirmationIdRouteWithChildren
  '/booking/form/$token': typeof BookingFormTokenRoute
  '/api/booking-invoice/$id/send': typeof ApiBookingInvoiceIdSendRoute
  '/api/public/booking-form/$token': typeof ApiPublicBookingFormTokenRoute
  '/book/confirmation/$id/chat': typeof BookConfirmationIdChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/connect'
    | '/explore'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-lab'
    | '/admin/analytics'
    | '/admin/booking-form-logs'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/chatbot-training'
    | '/admin/competitor-prices'
    | '/admin/complaints'
    | '/admin/contacts'
    | '/admin/content-manager'
    | '/admin/explore'
    | '/admin/handoff'
    | '/admin/health'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/pricing-calendar'
    | '/admin/rooms'
    | '/admin/routing-debug'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/telegram'
    | '/admin/training'
    | '/admin/walkthrough'
    | '/admin/webchat'
    | '/admin/whatsapp'
    | '/admin/whatsapp-corrections'
    | '/api/debug-db'
    | '/api/evolution'
    | '/api/place-photo'
    | '/api/public-site'
    | '/api/public-site-data'
    | '/api/queue-worker'
    | '/api/telegram'
    | '/lp/$slug'
    | '/rooms/$slug'
    | '/tour/$slug'
    | '/admin/'
    | '/book/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/booking-invoice/$id'
    | '/api/cron/booking-form-followup'
    | '/api/cron/booking-stuck-monitor'
    | '/api/cron/expire-bookings'
    | '/api/cron/process-wa-queue'
    | '/api/cron/run-article-schedules'
    | '/api/cron/sync-explore'
    | '/api/cron/wa-queue-safety-net'
    | '/api/cron/wa-summary-refresh'
    | '/api/public/health-check'
    | '/api/telegram/$agentKey'
    | '/book/confirmation/$id'
    | '/booking/form/$token'
    | '/api/booking-invoice/$id/send'
    | '/api/public/booking-form/$token'
    | '/book/confirmation/$id/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/connect'
    | '/explore'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-lab'
    | '/admin/analytics'
    | '/admin/booking-form-logs'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/chatbot-training'
    | '/admin/competitor-prices'
    | '/admin/complaints'
    | '/admin/contacts'
    | '/admin/content-manager'
    | '/admin/explore'
    | '/admin/handoff'
    | '/admin/health'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/pricing-calendar'
    | '/admin/rooms'
    | '/admin/routing-debug'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/telegram'
    | '/admin/training'
    | '/admin/walkthrough'
    | '/admin/webchat'
    | '/admin/whatsapp'
    | '/admin/whatsapp-corrections'
    | '/api/debug-db'
    | '/api/evolution'
    | '/api/place-photo'
    | '/api/public-site'
    | '/api/public-site-data'
    | '/api/queue-worker'
    | '/api/telegram'
    | '/lp/$slug'
    | '/rooms/$slug'
    | '/tour/$slug'
    | '/admin'
    | '/book'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/booking-invoice/$id'
    | '/api/cron/booking-form-followup'
    | '/api/cron/booking-stuck-monitor'
    | '/api/cron/expire-bookings'
    | '/api/cron/process-wa-queue'
    | '/api/cron/run-article-schedules'
    | '/api/cron/sync-explore'
    | '/api/cron/wa-queue-safety-net'
    | '/api/cron/wa-summary-refresh'
    | '/api/public/health-check'
    | '/api/telegram/$agentKey'
    | '/book/confirmation/$id'
    | '/booking/form/$token'
    | '/api/booking-invoice/$id/send'
    | '/api/public/booking-form/$token'
    | '/book/confirmation/$id/chat'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/connect'
    | '/explore'
    | '/llms.txt'
    | '/login'
    | '/mcp'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/ai-lab'
    | '/admin/analytics'
    | '/admin/booking-form-logs'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/chatbot-training'
    | '/admin/competitor-prices'
    | '/admin/complaints'
    | '/admin/contacts'
    | '/admin/content-manager'
    | '/admin/explore'
    | '/admin/handoff'
    | '/admin/health'
    | '/admin/media'
    | '/admin/notifications'
    | '/admin/pages'
    | '/admin/pricing-calendar'
    | '/admin/rooms'
    | '/admin/routing-debug'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/telegram'
    | '/admin/training'
    | '/admin/walkthrough'
    | '/admin/webchat'
    | '/admin/whatsapp'
    | '/admin/whatsapp-corrections'
    | '/api/debug-db'
    | '/api/evolution'
    | '/api/place-photo'
    | '/api/public-site'
    | '/api/public-site-data'
    | '/api/queue-worker'
    | '/api/telegram'
    | '/lp/$slug'
    | '/rooms/$slug'
    | '/tour/$slug'
    | '/admin/'
    | '/book/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/booking-invoice/$id'
    | '/api/cron/booking-form-followup'
    | '/api/cron/booking-stuck-monitor'
    | '/api/cron/expire-bookings'
    | '/api/cron/process-wa-queue'
    | '/api/cron/run-article-schedules'
    | '/api/cron/sync-explore'
    | '/api/cron/wa-queue-safety-net'
    | '/api/cron/wa-summary-refresh'
    | '/api/public/health-check'
    | '/api/telegram/$agentKey'
    | '/book/confirmation/$id'
    | '/booking/form/$token'
    | '/api/booking-invoice/$id/send'
    | '/api/public/booking-form/$token'
    | '/book/confirmation/$id/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChatRoute: typeof ChatRoute
  ConnectRoute: typeof ConnectRoute
  ExploreRoute: typeof ExploreRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiDebugDbRoute: typeof ApiDebugDbRoute
  ApiEvolutionRoute: typeof ApiEvolutionRoute
  ApiPlacePhotoRoute: typeof ApiPlacePhotoRoute
  ApiPublicSiteRoute: typeof ApiPublicSiteRoute
  ApiPublicSiteDataRoute: typeof ApiPublicSiteDataRoute
  ApiQueueWorkerRoute: typeof ApiQueueWorkerRoute
  ApiTelegramRoute: typeof ApiTelegramRouteWithChildren
  LpSlugRoute: typeof LpSlugRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
  TourSlugRoute: typeof TourSlugRoute
  BookIndexRoute: typeof BookIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiBookingInvoiceIdRoute: typeof ApiBookingInvoiceIdRouteWithChildren
  ApiCronBookingFormFollowupRoute: typeof ApiCronBookingFormFollowupRoute
  ApiCronBookingStuckMonitorRoute: typeof ApiCronBookingStuckMonitorRoute
  ApiCronExpireBookingsRoute: typeof ApiCronExpireBookingsRoute
  ApiCronProcessWaQueueRoute: typeof ApiCronProcessWaQueueRoute
  ApiCronRunArticleSchedulesRoute: typeof ApiCronRunArticleSchedulesRoute
  ApiCronSyncExploreRoute: typeof ApiCronSyncExploreRoute
  ApiCronWaQueueSafetyNetRoute: typeof ApiCronWaQueueSafetyNetRoute
  ApiCronWaSummaryRefreshRoute: typeof ApiCronWaSummaryRefreshRoute
  ApiPublicHealthCheckRoute: typeof ApiPublicHealthCheckRoute
  BookConfirmationIdRoute: typeof BookConfirmationIdRouteWithChildren
  BookingFormTokenRoute: typeof BookingFormTokenRoute
  ApiPublicBookingFormTokenRoute: typeof ApiPublicBookingFormTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-lab': {
      id: '/admin/ai-lab'
      path: '/ai-lab'
      fullPath: '/admin/ai-lab'
      preLoaderRoute: typeof AdminAiLabRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/booking-form-logs': {
      id: '/admin/booking-form-logs'
      path: '/booking-form-logs'
      fullPath: '/admin/booking-form-logs'
      preLoaderRoute: typeof AdminBookingFormLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chatbot-training': {
      id: '/admin/chatbot-training'
      path: '/chatbot-training'
      fullPath: '/admin/chatbot-training'
      preLoaderRoute: typeof AdminChatbotTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competitor-prices': {
      id: '/admin/competitor-prices'
      path: '/competitor-prices'
      fullPath: '/admin/competitor-prices'
      preLoaderRoute: typeof AdminCompetitorPricesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content-manager': {
      id: '/admin/content-manager'
      path: '/content-manager'
      fullPath: '/admin/content-manager'
      preLoaderRoute: typeof AdminContentManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/explore': {
      id: '/admin/explore'
      path: '/explore'
      fullPath: '/admin/explore'
      preLoaderRoute: typeof AdminExploreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/handoff': {
      id: '/admin/handoff'
      path: '/handoff'
      fullPath: '/admin/handoff'
      preLoaderRoute: typeof AdminHandoffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing-calendar': {
      id: '/admin/pricing-calendar'
      path: '/pricing-calendar'
      fullPath: '/admin/pricing-calendar'
      preLoaderRoute: typeof AdminPricingCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/routing-debug': {
      id: '/admin/routing-debug'
      path: '/routing-debug'
      fullPath: '/admin/routing-debug'
      preLoaderRoute: typeof AdminRoutingDebugRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/telegram': {
      id: '/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AdminTelegramRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/walkthrough': {
      id: '/admin/walkthrough'
      path: '/walkthrough'
      fullPath: '/admin/walkthrough'
      preLoaderRoute: typeof AdminWalkthroughRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webchat': {
      id: '/admin/webchat'
      path: '/webchat'
      fullPath: '/admin/webchat'
      preLoaderRoute: typeof AdminWebchatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp-corrections': {
      id: '/admin/whatsapp-corrections'
      path: '/whatsapp-corrections'
      fullPath: '/admin/whatsapp-corrections'
      preLoaderRoute: typeof AdminWhatsappCorrectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/debug-db': {
      id: '/api/debug-db'
      path: '/api/debug-db'
      fullPath: '/api/debug-db'
      preLoaderRoute: typeof ApiDebugDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evolution': {
      id: '/api/evolution'
      path: '/api/evolution'
      fullPath: '/api/evolution'
      preLoaderRoute: typeof ApiEvolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-photo': {
      id: '/api/place-photo'
      path: '/api/place-photo'
      fullPath: '/api/place-photo'
      preLoaderRoute: typeof ApiPlacePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-site': {
      id: '/api/public-site'
      path: '/api/public-site'
      fullPath: '/api/public-site'
      preLoaderRoute: typeof ApiPublicSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public-site-data': {
      id: '/api/public-site-data'
      path: '/api/public-site-data'
      fullPath: '/api/public-site-data'
      preLoaderRoute: typeof ApiPublicSiteDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queue-worker': {
      id: '/api/queue-worker'
      path: '/api/queue-worker'
      fullPath: '/api/queue-worker'
      preLoaderRoute: typeof ApiQueueWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-explore': {
      id: '/api/cron/sync-explore'
      path: '/api/cron/sync-explore'
      fullPath: '/api/cron/sync-explore'
      preLoaderRoute: typeof ApiCronSyncExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour/$slug': {
      id: '/tour/$slug'
      path: '/tour/$slug'
      fullPath: '/tour/$slug'
      preLoaderRoute: typeof TourSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-invoice/$id': {
      id: '/api/booking-invoice/$id'
      path: '/api/booking-invoice/$id'
      fullPath: '/api/booking-invoice/$id'
      preLoaderRoute: typeof ApiBookingInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/booking-stuck-monitor': {
      id: '/api/cron/booking-stuck-monitor'
      path: '/api/cron/booking-stuck-monitor'
      fullPath: '/api/cron/booking-stuck-monitor'
      preLoaderRoute: typeof ApiCronBookingStuckMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/expire-bookings': {
      id: '/api/cron/expire-bookings'
      path: '/api/cron/expire-bookings'
      fullPath: '/api/cron/expire-bookings'
      preLoaderRoute: typeof ApiCronExpireBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/process-wa-queue': {
      id: '/api/cron/process-wa-queue'
      path: '/api/cron/process-wa-queue'
      fullPath: '/api/cron/process-wa-queue'
      preLoaderRoute: typeof ApiCronProcessWaQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/wa-queue-safety-net': {
      id: '/api/cron/wa-queue-safety-net'
      path: '/api/cron/wa-queue-safety-net'
      fullPath: '/api/cron/wa-queue-safety-net'
      preLoaderRoute: typeof ApiCronWaQueueSafetyNetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/expire-bookings': {
      id: '/api/cron/expire-bookings'
      path: '/api/cron/expire-bookings'
      fullPath: '/api/cron/expire-bookings'
      preLoaderRoute: typeof ApiCronExpireBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health-check': {
      id: '/api/public/health-check'
      path: '/api/public/health-check'
      fullPath: '/api/public/health-check'
      preLoaderRoute: typeof ApiPublicHealthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-invoice/$id': {
      id: '/api/booking-invoice/$id'
      path: '/api/booking-invoice/$id'
      fullPath: '/api/booking-invoice/$id'
      preLoaderRoute: typeof ApiBookingInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmation/$id': {
      id: '/book/confirmation/$id'
      path: '/book/confirmation/$id'
      fullPath: '/book/confirmation/$id'
      preLoaderRoute: typeof BookConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/form/$token': {
      id: '/booking/form/$token'
      path: '/booking/form/$token'
      fullPath: '/booking/form/$token'
      preLoaderRoute: typeof BookingFormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/booking-invoice/$id/send': {
      id: '/api/booking-invoice/$id/send'
      path: '/send'
      fullPath: '/api/booking-invoice/$id/send'
      preLoaderRoute: typeof ApiBookingInvoiceIdSendRouteImport
      parentRoute: typeof ApiBookingInvoiceIdRoute
    }
    '/api/public/booking-form/$token': {
      id: '/api/public/booking-form/$token'
      path: '/api/public/booking-form/$token'
      fullPath: '/api/public/booking-form/$token'
      preLoaderRoute: typeof ApiPublicBookingFormTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/confirmation/$id/chat': {
      id: '/book/confirmation/$id/chat'
      path: '/chat'
      fullPath: '/book/confirmation/$id/chat'
      preLoaderRoute: typeof BookConfirmationIdChatRouteImport
      parentRoute: typeof BookConfirmationIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiLabRoute: typeof AdminAiLabRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingFormLogsRoute: typeof AdminBookingFormLogsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminChatbotTrainingRoute: typeof AdminChatbotTrainingRoute
  AdminCompetitorPricesRoute: typeof AdminCompetitorPricesRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminContentManagerRoute: typeof AdminContentManagerRoute
  AdminExploreRoute: typeof AdminExploreRoute
  AdminHandoffRoute: typeof AdminHandoffRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPricingCalendarRoute: typeof AdminPricingCalendarRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminRoutingDebugRoute: typeof AdminRoutingDebugRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTelegramRoute: typeof AdminTelegramRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  AdminWalkthroughRoute: typeof AdminWalkthroughRoute
  AdminWebchatRoute: typeof AdminWebchatRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminWhatsappCorrectionsRoute: typeof AdminWhatsappCorrectionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiLabRoute: AdminAiLabRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingFormLogsRoute: AdminBookingFormLogsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminChatbotTrainingRoute: AdminChatbotTrainingRoute,
  AdminCompetitorPricesRoute: AdminCompetitorPricesRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminContentManagerRoute: AdminContentManagerRoute,
  AdminExploreRoute: AdminExploreRoute,
  AdminHandoffRoute: AdminHandoffRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPricingCalendarRoute: AdminPricingCalendarRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminRoutingDebugRoute: AdminRoutingDebugRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTelegramRoute: AdminTelegramRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  AdminWalkthroughRoute: AdminWalkthroughRoute,
  AdminWebchatRoute: AdminWebchatRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminWhatsappCorrectionsRoute: AdminWhatsappCorrectionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiTelegramRouteChildren {
  ApiTelegramAgentKeyRoute: typeof ApiTelegramAgentKeyRoute
}

const ApiTelegramRouteChildren: ApiTelegramRouteChildren = {
  ApiTelegramAgentKeyRoute: ApiTelegramAgentKeyRoute,
}

const ApiTelegramRouteWithChildren = ApiTelegramRoute._addFileChildren(
  ApiTelegramRouteChildren,
)

interface ApiBookingInvoiceIdRouteChildren {
  ApiBookingInvoiceIdSendRoute: typeof ApiBookingInvoiceIdSendRoute
}

const ApiBookingInvoiceIdRouteChildren: ApiBookingInvoiceIdRouteChildren = {
  ApiBookingInvoiceIdSendRoute: ApiBookingInvoiceIdSendRoute,
}

const ApiBookingInvoiceIdRouteWithChildren =
  ApiBookingInvoiceIdRoute._addFileChildren(ApiBookingInvoiceIdRouteChildren)

interface BookConfirmationIdRouteChildren {
  BookConfirmationIdChatRoute: typeof BookConfirmationIdChatRoute
}

const BookConfirmationIdRouteChildren: BookConfirmationIdRouteChildren = {
  BookConfirmationIdChatRoute: BookConfirmationIdChatRoute,
}

const BookConfirmationIdRouteWithChildren =
  BookConfirmationIdRoute._addFileChildren(BookConfirmationIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChatRoute: ChatRoute,
  ConnectRoute: ConnectRoute,
  ExploreRoute: ExploreRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiDebugDbRoute: ApiDebugDbRoute,
  ApiEvolutionRoute: ApiEvolutionRoute,
  ApiPlacePhotoRoute: ApiPlacePhotoRoute,
  ApiPublicSiteRoute: ApiPublicSiteRoute,
  ApiPublicSiteDataRoute: ApiPublicSiteDataRoute,
  ApiQueueWorkerRoute: ApiQueueWorkerRoute,
  ApiTelegramRoute: ApiTelegramRouteWithChildren,
  LpSlugRoute: LpSlugRoute,
  RoomsSlugRoute: RoomsSlugRoute,
  TourSlugRoute: TourSlugRoute,
  BookIndexRoute: BookIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiBookingInvoiceIdRoute: ApiBookingInvoiceIdRouteWithChildren,
  ApiCronBookingFormFollowupRoute: ApiCronBookingFormFollowupRoute,
  ApiCronBookingStuckMonitorRoute: ApiCronBookingStuckMonitorRoute,
  ApiCronExpireBookingsRoute: ApiCronExpireBookingsRoute,
  ApiCronProcessWaQueueRoute: ApiCronProcessWaQueueRoute,
  ApiCronRunArticleSchedulesRoute: ApiCronRunArticleSchedulesRoute,
  ApiCronSyncExploreRoute: ApiCronSyncExploreRoute,
  ApiCronWaQueueSafetyNetRoute: ApiCronWaQueueSafetyNetRoute,
  ApiCronWaSummaryRefreshRoute: ApiCronWaSummaryRefreshRoute,
  ApiPublicHealthCheckRoute: ApiPublicHealthCheckRoute,
  BookConfirmationIdRoute: BookConfirmationIdRouteWithChildren,
  BookingFormTokenRoute: BookingFormTokenRoute,
  ApiPublicBookingFormTokenRoute: ApiPublicBookingFormTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
