/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as BookIndexRouteImport } from './routes/book.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'
import { Route as ApiFonnteRouteImport } from './routes/api.fonnte'
import { Route as AdminWhatsappRouteImport } from './routes/admin/whatsapp'
import { Route as AdminTrainingRouteImport } from './routes/admin/training'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSeoRouteImport } from './routes/admin/seo'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminPricingRouteImport } from './routes/admin/pricing'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminExploreRouteImport } from './routes/admin/explore'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AdminBookingsRouteImport } from './routes/admin/bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAiLabRouteImport } from './routes/admin/ai-lab'
import { Route as AdminAiRouteImport } from './routes/admin/ai'
import { Route as BookConfirmationIdRouteImport } from './routes/book/confirmation/$id'
import { Route as ApiCronSyncExploreRouteImport } from './routes/api.cron.sync-explore'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIndexRoute = BookIndexRouteImport.update({
  id: '/book/',
  path: '/book/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFonnteRoute = ApiFonnteRouteImport.update({
  id: '/api/fonnte',
  path: '/api/fonnte',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainingRoute = AdminTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExploreRoute = AdminExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiLabRoute = AdminAiLabRouteImport.update({
  id: '/ai-lab',
  path: '/ai-lab',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const BookConfirmationIdRoute = BookConfirmationIdRouteImport.update({
  id: '/book/confirmation/$id',
  path: '/book/confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSyncExploreRoute = ApiCronSyncExploreRouteImport.update({
  id: '/api/cron/sync-explore',
  path: '/api/cron/sync-explore',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/ai-lab': typeof AdminAiLabRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/explore': typeof AdminExploreRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/api/fonnte': typeof ApiFonnteRoute
  '/lp/$slug': typeof LpSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/book/': typeof BookIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/cron/sync-explore': typeof ApiCronSyncExploreRoute
  '/book/confirmation/$id': typeof BookConfirmationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/ai-lab': typeof AdminAiLabRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/explore': typeof AdminExploreRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/api/fonnte': typeof ApiFonnteRoute
  '/lp/$slug': typeof LpSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/book': typeof BookIndexRoute
  '/rooms': typeof RoomsIndexRoute
  '/api/cron/sync-explore': typeof ApiCronSyncExploreRoute
  '/book/confirmation/$id': typeof BookConfirmationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/explore': typeof ExploreRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/ai-lab': typeof AdminAiLabRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/explore': typeof AdminExploreRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/training': typeof AdminTrainingRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/api/fonnte': typeof ApiFonnteRoute
  '/lp/$slug': typeof LpSlugRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/book/': typeof BookIndexRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/cron/sync-explore': typeof ApiCronSyncExploreRoute
  '/book/confirmation/$id': typeof BookConfirmationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/explore'
    | '/llms.txt'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/ai'
    | '/admin/ai-lab'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/explore'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/pricing'
    | '/admin/rooms'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/training'
    | '/admin/whatsapp'
    | '/api/fonnte'
    | '/lp/$slug'
    | '/rooms/$slug'
    | '/admin/'
    | '/book/'
    | '/rooms/'
    | '/api/cron/sync-explore'
    | '/book/confirmation/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/llms.txt'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/ai'
    | '/admin/ai-lab'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/explore'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/pricing'
    | '/admin/rooms'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/training'
    | '/admin/whatsapp'
    | '/api/fonnte'
    | '/lp/$slug'
    | '/rooms/$slug'
    | '/admin'
    | '/book'
    | '/rooms'
    | '/api/cron/sync-explore'
    | '/book/confirmation/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/explore'
    | '/llms.txt'
    | '/login'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/ai'
    | '/admin/ai-lab'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/calendar'
    | '/admin/explore'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/pricing'
    | '/admin/rooms'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/training'
    | '/admin/whatsapp'
    | '/api/fonnte'
    | '/lp/$slug'
    | '/rooms/$slug'
    | '/admin/'
    | '/book/'
    | '/rooms/'
    | '/api/cron/sync-explore'
    | '/book/confirmation/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiFonnteRoute: typeof ApiFonnteRoute
  LpSlugRoute: typeof LpSlugRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
  BookIndexRoute: typeof BookIndexRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  ApiCronSyncExploreRoute: typeof ApiCronSyncExploreRoute
  BookConfirmationIdRoute: typeof BookConfirmationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/': {
      id: '/book/'
      path: '/book'
      fullPath: '/book/'
      preLoaderRoute: typeof BookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fonnte': {
      id: '/api/fonnte'
      path: '/api/fonnte'
      fullPath: '/api/fonnte'
      preLoaderRoute: typeof ApiFonnteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/training': {
      id: '/admin/training'
      path: '/training'
      fullPath: '/admin/training'
      preLoaderRoute: typeof AdminTrainingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/explore': {
      id: '/admin/explore'
      path: '/explore'
      fullPath: '/admin/explore'
      preLoaderRoute: typeof AdminExploreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-lab': {
      id: '/admin/ai-lab'
      path: '/ai-lab'
      fullPath: '/admin/ai-lab'
      preLoaderRoute: typeof AdminAiLabRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/book/confirmation/$id': {
      id: '/book/confirmation/$id'
      path: '/book/confirmation/$id'
      fullPath: '/book/confirmation/$id'
      preLoaderRoute: typeof BookConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sync-explore': {
      id: '/api/cron/sync-explore'
      path: '/api/cron/sync-explore'
      fullPath: '/api/cron/sync-explore'
      preLoaderRoute: typeof ApiCronSyncExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAiLabRoute: typeof AdminAiLabRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminExploreRoute: typeof AdminExploreRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrainingRoute: typeof AdminTrainingRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAiLabRoute: AdminAiLabRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminExploreRoute: AdminExploreRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrainingRoute: AdminTrainingRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ExploreRoute: ExploreRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiFonnteRoute: ApiFonnteRoute,
  LpSlugRoute: LpSlugRoute,
  RoomsSlugRoute: RoomsSlugRoute,
  BookIndexRoute: BookIndexRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  ApiCronSyncExploreRoute: ApiCronSyncExploreRoute,
  BookConfirmationIdRoute: BookConfirmationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
